version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    # Complexity & size
    - funlen
    - nestif

    # DRY
    - dupl
    - goconst

    # Hardcode prevention
    - usestdlibvars

    # Security
    - gosec

    # Code quality
    - gocritic
    - noctx
    - bodyclose
    - errorlint
    - perfsprint

  settings:
    funlen:
      lines: 200
      statements: 100
    nestif:
      min-complexity: 10
    dupl:
      threshold: 150
    goconst:
      min-len: 3
      min-occurrences: 4
    gosec:
      excludes:
        - G104
        - G304
        - G402  # TLS InsecureSkipVerify — needed for stealth HTTP

  exclusions:
    presets:
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - funlen
          - dupl
          - gosec
          - goconst
